// COURSE: CSCI1620
// TERM: Spring 2019
// 
// NAME: Dr. Dorn
// RESOURCES: No external code or references were used 
//		      in creating this file.

/////////////////////////////////////////////////
//DO NOT EDIT THIS FILE.  CHANGING THIS CODE
//IS NOT REQUIRED BY THE ASSIGNMENT.
/////////////////////////////////////////////////

/**
 * This class is a small stub class that is solely responsible
 * for kicking off the BrickBreaker graphical user interface
 * which is included through a pre-compiled library.
 * 
 * @author bdorn
 *
 */
public class BrickBreakerApp
{
	/**
	 * Initializes the graphical user interface for the game.
	 * 
	 * @param args Command line arguments, which are not used.
	 */
	public static void main(String[] args)
	{
		BrickBreakerGUI.main(args);
	}
}
